spring.application.name=recipe-manager

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/recipe_manager}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.cache=false